;EQUIPO 3 - BUAP - FCC

;LEER EL 1er. NUMERO
LEER:
    MOV AH, 01H ; DEFINE EL SERVICIO 01H_PARA_LECTURA_DE 1_CARACTER
    INT 21H     ;DEJA" EL CODIGO ASCII DEL CARACTER LEIDO EN AL
               
    CMP AL, 30H ; DIGITO MENOR AL '0'
    JL LEER
    CMP AL, 39H
    JG LEER   ; DIGITO MAYOR AL '9'
                 ;REALIZA LA CONV DE ASCII A HEXA
    SUB AL, 30H
    MOV NUM1, AL

;LEER EL 2o. NUMERO
LEER2:
    MOV AH, 01H  ;DEFINE EL SERVICI0 01H PARA_LECTURA_DE 1_CARACTER
    INT 21H      ;DEJA EL CODIGO ASCII DEL CARACTER LEIDO EN AL

    CMP AL, 30H ; DIGITO MENOR AL '0'
    JL LEER2
    CMP AL, 39H   ; DIGITO MAYOR AL '9'
    JG LEER2
                 ;REALIZA LA CONV DE ASCII A HEXA
    SUB AL, 30H
    MOV NUM2, AL  
    
    
    
;SUMA 
ADD AL, NUM1 ; NUM1 + NUM2
MOV SUM, AL  ;GUARDO EL RESULTADO 


;RESTA
MOV AL, NUM1   
SUB AL, NUM2 ;NUM1 - NUM2
MOV RES, AL  ;GUARDO EL RESULTADO


;MULT
MOV AL, NUM1
MOV CL, NUM2
MUL CL  ;AL*CL  (NUM1*NUM2)
MOV MULTI, AL
               
                 
;DIV 
MOV AL, NUM1
MOV BL, NUM2
DIV BL ;AL/BL (NUM1/NUM2)
MOV COCI, AL
MOV RESI, AH                
             
             
INT 20H       

NUM1   DB 00H
NUM2   DB 00H
SUM    DB 00
RES    DB 00   
MULTI  DB 00H 
COCI   DB 00
RESI   DB 00H